.TH ARMEE 1 armee
.SH NAME
Armee \- quick german subtitle -> anki flashcard converter
.SH SYNOPSIS
.B armee
.IR text
.RB [path/to/audio]
.SH DESCRIPTION
.B Armee
is a simple to use tool to search definitions on the german wiktionary and push them into an anki card
.SH SHORTCUTS
.SS Movement
.INDENT 0.0
.TP
.B hjkl
Let you move inside squares
.TP
.B HJKL
Let you move between squares
.SP
.SS Interacting with text
.INDENT 0.0
.TP
.B c
Adds currently selected item in full to the final string
.TP
.B <space>
Adds currently selected item without the begining parentheses to the final string
.TP
.B n
Queries anki for the current selected text
.TP
.B f
Takes the currently selected text but prompts the user as to what to search in the dictionary
.SP
.SS Exit
.INDENT 0.0
.TP
.B q
Exits without doing anything
.TP
.B O
Bolds selected text, pushes entire string, no prompt
.TP
.B I
Bolds selected text, pushes entire string, gui prompt
.TP
.B u
Bolds selected text, pushes string without word names, no prompt
.TP
.B U
Bolds selected text, pushes string without word names, gui prompt
.TP
.B p
Doesn't bold selected text, pushes string without word names, no prompt
.TP
.B p
Doesn't bold selected text, pushes string without word names, gui prompt
.TP

